# This is a basic workflow to help you get started with Actions

name: continuous integration pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Job: Run unit tests
  unit_test:
    runs-on: ubuntu-latest
    container: lironavon/docker-puppeteer-container:14.16.0
    steps:
      - uses: actions/checkout@v2

      - name: Install stuff
        run:
          npm install
      - name: Run test
        run:
          npm run test-unit

  # Job: Lint javascript files
  lint_js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install stuff
        run:
          npm install
      - name: run_linter
        run:
          npm run jslint

  # Job: Lint html files
  lint_html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install stuff
        run:
          npm install
      - name: run_linter
        run:
          npm run htmllint

  # Job: Lint html files
  lint_css:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install stuff
        run:
          npm install
      - name: run_linter
        run:
          npm run csslint

  # Job: Generate documentation, put output in ./docs
  generate_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install stuff
        run:
          npm install
      - name: document
        run:
          npm run doc
      - uses: stefanzweifel/git-auto-commit-action@v4