# This is a basic workflow to help you get started with Actions

name: continuous_integration

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Job: Run unit tests
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install stuff
        run:
          npm install
      - name: Run test
        run:
          npm test

  # Job: Lint files
  lint_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install stuff
        run:
          npm install
      - name: run_linter
        run:
          npx run lint

  # Job: Generate documentation, put output in ./docs
  generate_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install stuff
        run:
          npm install
      - name: document
        run:
          npm run doc
      - uses: stefanzweifel/git-auto-commit-action@v4
